vich_uploader:
    db_driver: orm

    mappings:
        images_galerie:
            uri_prefix: '%app.path.images_galerie%'
            upload_destination: '%kernel.project_dir%/public%app.path.images_galerie%'

        pdf_facture:
            uri_prefix: '%app.path.pdf_facture%'
            upload_destination: '%kernel.project_dir%/public%app.path.pdf_facture%'
